<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-02">

<title>T20 — Z₂ Lattice Gauge Theory Monte Carlo – TimesArrow</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-59a97b6816e8c0b74c7adf5829d641d7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">TimesArrow</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../dashboard.html"> 
<span class="menu-text">Dashboard</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-simulations" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Simulations</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-simulations">    
        <li>
    <a class="dropdown-item" href="../tasks/t31-deconfinement-polyakov.html">
 <span class="dropdown-text">T31 — Deconfinement (Polyakov)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t31-signed-volume.html">
 <span class="dropdown-text">T31 — Signed Volume (Archived)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t25-volume-operator.html">
 <span class="dropdown-text">T25 — Volume Operator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t20-z2-lgt.html">
 <span class="dropdown-text">T20 — Z₂ LGT Monte Carlo</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t23-entanglement.html">
 <span class="dropdown-text">T23 — Entanglement Entropy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t22-spin-foam.html">
 <span class="dropdown-text">T22 — Spin Foam Amplitudes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t21-czx-peps.html">
 <span class="dropdown-text">T21 — CZX PEPS</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t24-domain-walls.html">
 <span class="dropdown-text">T24 — Domain Walls</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks/t26-coupled-matter.html">
 <span class="dropdown-text">T26 — Coupled Matter</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tasks/t31-deconfinement-polyakov.html">Tasks</a></li><li class="breadcrumb-item"><a href="../tasks/t20-z2-lgt.html">T20 — Z₂ Lattice Gauge Theory Monte Carlo</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TimesArrow Numerics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulation Dashboard</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Tasks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t31-deconfinement-polyakov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T31 — Deconfinement via Polyakov Loop</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t31-signed-volume.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T31 — Signed Volume Observable for Z₂ Gauge Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t25-volume-operator.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T25 — Volume Operator Extension</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t20-z2-lgt.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">T20 — Z₂ Lattice Gauge Theory Monte Carlo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t23-entanglement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T23 — Entanglement Entropy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t22-spin-foam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T22 — Spin Foam Amplitudes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t21-czx-peps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T21 — CZX PEPS Ground State</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t24-domain-walls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T24 — Domain Wall Dynamics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tasks/t26-coupled-matter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T26 — Coupled Spin Network + Matter</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#objective" id="toc-objective" class="nav-link active" data-scroll-target="#objective">Objective</a></li>
  <li><a href="#status" id="toc-status" class="nav-link" data-scroll-target="#status">Status</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory">Theory</a>
  <ul class="collapse">
  <li><a href="#observables" id="toc-observables" class="nav-link" data-scroll-target="#observables">Observables</a></li>
  <li><a href="#phase-structure" id="toc-phase-structure" class="nav-link" data-scroll-target="#phase-structure">Phase Structure</a></li>
  </ul></li>
  <li><a href="#architecture" id="toc-architecture" class="nav-link" data-scroll-target="#architecture">Architecture</a>
  <ul class="collapse">
  <li><a href="#ts-quantum-reusable-lattice-gauge-theory" id="toc-ts-quantum-reusable-lattice-gauge-theory" class="nav-link" data-scroll-target="#ts-quantum-reusable-lattice-gauge-theory">ts-quantum (reusable lattice gauge theory)</a></li>
  <li><a href="#timesarrow-simulation-setup" id="toc-timesarrow-simulation-setup" class="nav-link" data-scroll-target="#timesarrow-simulation-setup">timesarrow (simulation setup)</a></li>
  </ul></li>
  <li><a href="#phase-1-2d-square-lattice-complete" id="toc-phase-1-2d-square-lattice-complete" class="nav-link" data-scroll-target="#phase-1-2d-square-lattice-complete">Phase 1: 2D Square Lattice (Complete)</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#results-l-8-fast-validation" id="toc-results-l-8-fast-validation" class="nav-link" data-scroll-target="#results-l-8-fast-validation">Results: L = 8 (Fast Validation)</a></li>
  <li><a href="#results-l-16-production" id="toc-results-l-16-production" class="nav-link" data-scroll-target="#results-l-16-production">Results: L = 16 (Production)</a></li>
  <li><a href="#figures" id="toc-figures" class="nav-link" data-scroll-target="#figures">Figures</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a></li>
  </ul></li>
  <li><a href="#phase-2-finite-size-scaling-complete" id="toc-phase-2-finite-size-scaling-complete" class="nav-link" data-scroll-target="#phase-2-finite-size-scaling-complete">Phase 2: Finite-Size Scaling (Complete)</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#plaquette-expectation-values" id="toc-plaquette-expectation-values" class="nav-link" data-scroll-target="#plaquette-expectation-values">Plaquette Expectation Values</a></li>
  <li><a href="#key-observables-by-lattice-size" id="toc-key-observables-by-lattice-size" class="nav-link" data-scroll-target="#key-observables-by-lattice-size">Key Observables by Lattice Size</a></li>
  <li><a href="#binder-cumulant-analysis" id="toc-binder-cumulant-analysis" class="nav-link" data-scroll-target="#binder-cumulant-analysis">Binder Cumulant Analysis</a></li>
  <li><a href="#finite-size-scaling-conclusions" id="toc-finite-size-scaling-conclusions" class="nav-link" data-scroll-target="#finite-size-scaling-conclusions">Finite-Size Scaling Conclusions</a></li>
  <li><a href="#data-files" id="toc-data-files" class="nav-link" data-scroll-target="#data-files">Data Files</a></li>
  <li><a href="#reproduction" id="toc-reproduction" class="nav-link" data-scroll-target="#reproduction">Reproduction</a></li>
  </ul></li>
  <li><a href="#phase-3-3d-cubic-lattice-complete" id="toc-phase-3-3d-cubic-lattice-complete" class="nav-link" data-scroll-target="#phase-3-3d-cubic-lattice-complete">Phase 3: 3D Cubic Lattice (Complete)</a>
  <ul class="collapse">
  <li><a href="#overview-1" id="toc-overview-1" class="nav-link" data-scroll-target="#overview-1">Overview</a></li>
  <li><a href="#plaquette-expectation-values-1" id="toc-plaquette-expectation-values-1" class="nav-link" data-scroll-target="#plaquette-expectation-values-1">Plaquette Expectation Values</a></li>
  <li><a href="#susceptibility-peak-signals-critical-region" id="toc-susceptibility-peak-signals-critical-region" class="nav-link" data-scroll-target="#susceptibility-peak-signals-critical-region">Susceptibility (Peak Signals Critical Region)</a></li>
  <li><a href="#binder-cumulant" id="toc-binder-cumulant" class="nav-link" data-scroll-target="#binder-cumulant">Binder Cumulant</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key Findings</a></li>
  <li><a href="#wilson-loop-results-l-8" id="toc-wilson-loop-results-l-8" class="nav-link" data-scroll-target="#wilson-loop-results-l-8">Wilson Loop Results (L = 8)</a></li>
  <li><a href="#string-tension-analysis" id="toc-string-tension-analysis" class="nav-link" data-scroll-target="#string-tension-analysis">String Tension Analysis</a></li>
  <li><a href="#confinement-deconfinement-signature" id="toc-confinement-deconfinement-signature" class="nav-link" data-scroll-target="#confinement-deconfinement-signature">Confinement-Deconfinement Signature</a></li>
  <li><a href="#multi-lattice-comparison-fine-grained-β" id="toc-multi-lattice-comparison-fine-grained-β" class="nav-link" data-scroll-target="#multi-lattice-comparison-fine-grained-β">Multi-Lattice Comparison (Fine-Grained β)</a></li>
  <li><a href="#data-files-1" id="toc-data-files-1" class="nav-link" data-scroll-target="#data-files-1">Data Files</a></li>
  <li><a href="#corrected-3d-interpretation" id="toc-corrected-3d-interpretation" class="nav-link" data-scroll-target="#corrected-3d-interpretation">Corrected 3D Interpretation</a></li>
  </ul></li>
  <li><a href="#implementation-details" id="toc-implementation-details" class="nav-link" data-scroll-target="#implementation-details">Implementation Details</a></li>
  <li><a href="#implementation-details-1" id="toc-implementation-details-1" class="nav-link" data-scroll-target="#implementation-details-1">Implementation Details</a>
  <ul class="collapse">
  <li><a href="#rust-framework-t27" id="toc-rust-framework-t27" class="nav-link" data-scroll-target="#rust-framework-t27">Rust Framework (T27)</a></li>
  <li><a href="#code-example" id="toc-code-example" class="nav-link" data-scroll-target="#code-example">Code Example</a></li>
  </ul></li>
  <li><a href="#phase-3b-ising-fss-reanalysis-t32-t20d" id="toc-phase-3b-ising-fss-reanalysis-t32-t20d" class="nav-link" data-scroll-target="#phase-3b-ising-fss-reanalysis-t32-t20d">Phase 3b: Ising FSS Reanalysis (T32-T20d)</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#analysis-script" id="toc-analysis-script" class="nav-link" data-scroll-target="#analysis-script">Analysis Script</a></li>
  <li><a href="#pseudo-critical-couplings" id="toc-pseudo-critical-couplings" class="nav-link" data-scroll-target="#pseudo-critical-couplings">Pseudo-Critical Couplings</a></li>
  <li><a href="#thermodynamic-extrapolation" id="toc-thermodynamic-extrapolation" class="nav-link" data-scroll-target="#thermodynamic-extrapolation">Thermodynamic Extrapolation</a></li>
  <li><a href="#scaling-collapse" id="toc-scaling-collapse" class="nav-link" data-scroll-target="#scaling-collapse">Scaling Collapse</a></li>
  <li><a href="#caveats-and-limitations" id="toc-caveats-and-limitations" class="nav-link" data-scroll-target="#caveats-and-limitations">Caveats and Limitations</a></li>
  <li><a href="#figures-1" id="toc-figures-1" class="nav-link" data-scroll-target="#figures-1">Figures</a></li>
  </ul></li>
  <li><a href="#phase-3b-corrected-finite-size-scaling-status" id="toc-phase-3b-corrected-finite-size-scaling-status" class="nav-link" data-scroll-target="#phase-3b-corrected-finite-size-scaling-status">Phase 3b: Corrected Finite-Size Scaling Status</a>
  <ul class="collapse">
  <li><a href="#retained-data" id="toc-retained-data" class="nav-link" data-scroll-target="#retained-data">Retained Data</a></li>
  <li><a href="#reanalysis-requirements" id="toc-reanalysis-requirements" class="nav-link" data-scroll-target="#reanalysis-requirements">Reanalysis Requirements</a></li>
  <li><a href="#key-files" id="toc-key-files" class="nav-link" data-scroll-target="#key-files">Key Files</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tasks/t31-deconfinement-polyakov.html">Tasks</a></li><li class="breadcrumb-item"><a href="../tasks/t20-z2-lgt.html">T20 — Z₂ Lattice Gauge Theory Monte Carlo</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">T20 — Z₂ Lattice Gauge Theory Monte Carlo</h1>
<p class="subtitle lead">Confinement-deconfinement transition</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 2, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 14, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<p><em>Last updated: 2026-07-10 18:45 IST</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>📊 Live Dashboard
</div>
</div>
<div class="callout-body-container callout-body">
<p>View all simulation runs and figures: <strong><a href="../dashboard.html">TimesArrow Numerics Dashboard →</a></strong></p>
</div>
</div>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<p>Classical Monte Carlo simulation of Z₂ gauge theory to demonstrate the confinement-deconfinement transition that underpins the paper’s central claim.</p>
</section>
<section id="status" class="level2">
<h2 class="anchored" data-anchor-id="status">Status</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 38%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Description</th>
<th>Status</th>
<th>Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Phase 1</td>
<td>2D square lattice, critical β identification</td>
<td>✅ Complete</td>
<td>2026-06-24</td>
</tr>
<tr class="even">
<td>Phase 2</td>
<td>Finite-size scaling (L = 8–24)</td>
<td>✅ Complete</td>
<td>2026-06-25</td>
</tr>
<tr class="odd">
<td>Phase 3</td>
<td>3D cubic lattice (L=4,6,8)</td>
<td>✅ Complete</td>
<td>2026-06-25</td>
</tr>
<tr class="even">
<td>Phase 3b</td>
<td>3D FSS correction and reanalysis</td>
<td>🔄 In progress</td>
<td>2026-07-05</td>
</tr>
<tr class="odd">
<td>Phase 3b</td>
<td>3D Wilson loops &amp; string tension (L=8)</td>
<td>✅ Complete</td>
<td>2026-06-26</td>
</tr>
</tbody>
</table>
<p><strong>Corrected status</strong>: The 3D pure Z₂ gauge transition is continuous and belongs to the 3D Ising universality class. Existing simulations resolve the established critical region near β ≈ 0.76, but the previous first-order interpretation and claimed precision determination are withdrawn pending a controlled reanalysis.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Correction notice
</div>
</div>
<div class="callout-body-container callout-body">
<p>The plaquette Binder limit near <span class="math inline">\(2/3\)</span> is not evidence for a first-order transition, and the earlier double-peaked histograms were synthetic illustrations rather than sampled distributions. The raw simulation data are retained; the superseded interpretation is not used in the manuscript.</p>
</div>
</div>
</section>
<section id="theory" class="level2">
<h2 class="anchored" data-anchor-id="theory">Theory</h2>
<p>The Z₂ gauge theory action:</p>
<p><span class="math display">\[
S = -\beta \sum_{\square} \prod_{e \in \square} \sigma_e
\]</span></p>
<p>where <span class="math inline">\(\sigma_e \in \{+1, -1\}\)</span> are link variables and <span class="math inline">\(\beta\)</span> is the inverse coupling (temperature).</p>
<section id="observables" class="level3">
<h3 class="anchored" data-anchor-id="observables">Observables</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Observable</th>
<th>Formula</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Average plaquette</td>
<td><span class="math inline">\(\langle P \rangle = \frac{1}{N_{\square}} \sum_{\square} \prod_{e \in \square} \sigma_e\)</span></td>
<td>Order parameter</td>
</tr>
<tr class="even">
<td>Specific heat</td>
<td><span class="math inline">\(C_V = \beta^2(\langle P^2 \rangle - \langle P \rangle^2)\)</span></td>
<td>Critical fluctuations</td>
</tr>
<tr class="odd">
<td>Susceptibility</td>
<td><span class="math inline">\(\chi = L^2(\langle P^2 \rangle - \langle P \rangle^2)\)</span></td>
<td>Response function</td>
</tr>
<tr class="even">
<td>Binder cumulant</td>
<td><span class="math inline">\(U = 1 - \langle P^4 \rangle/(3\langle P^2 \rangle^2)\)</span></td>
<td>Finite-size scaling</td>
</tr>
<tr class="odd">
<td>Wilson loop</td>
<td><span class="math inline">\(W(\gamma) = \langle \prod_{e \in \gamma} \sigma_e \rangle\)</span></td>
<td>Confinement test</td>
</tr>
</tbody>
</table>
</section>
<section id="phase-structure" class="level3">
<h3 class="anchored" data-anchor-id="phase-structure">Phase Structure</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 36%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Wilson loop</th>
<th>Order parameter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Confined (<span class="math inline">\(\beta &lt; \beta_c\)</span>)</td>
<td>Area law: <span class="math inline">\(W \sim e^{-\alpha A}\)</span></td>
<td><span class="math inline">\(\langle P \rangle \ll 1\)</span></td>
</tr>
<tr class="even">
<td>Deconfined (<span class="math inline">\(\beta &gt; \beta_c\)</span>)</td>
<td>Perimeter law: <span class="math inline">\(W \sim e^{-\beta P}\)</span></td>
<td><span class="math inline">\(\langle P \rangle \to 1\)</span></td>
</tr>
</tbody>
</table>
<p>Critical coupling (exact): <span class="math inline">\(\beta_c = \frac{1}{2}\ln(1+\sqrt{2}) \approx 0.4407\)</span></p>
</section>
</section>
<section id="architecture" class="level2">
<h2 class="anchored" data-anchor-id="architecture">Architecture</h2>
<p><strong>General tools → <code>ts-quantum</code>, specific sim → <code>timesarrow/numerics/</code></strong></p>
<section id="ts-quantum-reusable-lattice-gauge-theory" class="level3">
<h3 class="anchored" data-anchor-id="ts-quantum-reusable-lattice-gauge-theory">ts-quantum (reusable lattice gauge theory)</h3>
<ul>
<li><code>src/lattice/geometry.ts</code> — Lattice types (2D square, 2D triangular, 3D cubic)</li>
<li><code>src/lattice/gaugeField.ts</code> — <code>Z2GaugeField</code> class (link variables ±1)</li>
<li><code>src/lattice/action.ts</code> — Wilson action and delta-S computation</li>
<li><code>src/lattice/monteCarlo.ts</code> — Metropolis algorithm, thermalization, measurement</li>
<li><code>src/lattice/observables.ts</code> — Plaquette average, specific heat, Wilson loops, Binder cumulant, jackknife error</li>
</ul>
</section>
<section id="timesarrow-simulation-setup" class="level3">
<h3 class="anchored" data-anchor-id="timesarrow-simulation-setup">timesarrow (simulation setup)</h3>
<ul>
<li><code>numerics/src/scripts/t20-z2-lgt-phase1.ts</code> — 2D square lattice parameter sweep</li>
<li><code>numerics/src/scripts/t20-z2-lgt-phase2.ts</code> — 2D triangular lattice</li>
<li><code>numerics/src/scripts/t20-z2-lgt-phase3.ts</code> — 3D cubic lattice (paper target)</li>
</ul>
<hr>
</section>
</section>
<section id="phase-1-2d-square-lattice-complete" class="level2">
<h2 class="anchored" data-anchor-id="phase-1-2d-square-lattice-complete">Phase 1: 2D Square Lattice (Complete)</h2>
<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<ul>
<li>Lattice: <span class="math inline">\(L \times L\)</span> square with periodic boundary conditions</li>
<li>Plaquettes: squares with 4 links each</li>
<li>Algorithm: Metropolis Monte Carlo with single-link updates</li>
<li>Critical coupling (exact): <span class="math inline">\(\beta_c = \frac{1}{2}\ln(1+\sqrt{2}) \approx 0.4407\)</span></li>
</ul>
</section>
<section id="results-l-8-fast-validation" class="level3">
<h3 class="anchored" data-anchor-id="results-l-8-fast-validation">Results: L = 8 (Fast Validation)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lattice size <span class="math inline">\(L\)</span></td>
<td>8</td>
</tr>
<tr class="even">
<td>Thermalization sweeps</td>
<td>1,000</td>
</tr>
<tr class="odd">
<td>Measurement sweeps</td>
<td>5,000</td>
</tr>
<tr class="even">
<td>Measure every</td>
<td>5 sweeps</td>
</tr>
<tr class="odd">
<td>Bin size (error analysis)</td>
<td>20</td>
</tr>
<tr class="even">
<td>Wall-clock time</td>
<td>~5 minutes</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\beta\)</span></th>
<th><span class="math inline">\(\langle P \rangle\)</span></th>
<th>Error</th>
<th>Phase</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.10</td>
<td>0.0969</td>
<td>±0.0036</td>
<td>Confined</td>
</tr>
<tr class="even">
<td>0.20</td>
<td>0.1994</td>
<td>±0.0042</td>
<td>Confined</td>
</tr>
<tr class="odd">
<td>0.30</td>
<td>0.3012</td>
<td>±0.0039</td>
<td>Confined</td>
</tr>
<tr class="even">
<td>0.40</td>
<td>0.3748</td>
<td>±0.0039</td>
<td>Near critical</td>
</tr>
<tr class="odd">
<td><strong>0.44</strong></td>
<td><strong>0.4162</strong></td>
<td><strong>±0.0035</strong></td>
<td><strong>Critical</strong></td>
</tr>
<tr class="even">
<td>0.50</td>
<td>0.4608</td>
<td>±0.0033</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>0.60</td>
<td>0.5335</td>
<td>±0.0030</td>
<td>Deconfined</td>
</tr>
<tr class="even">
<td>0.80</td>
<td>0.6645</td>
<td>±0.0028</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>1.00</td>
<td>0.7572</td>
<td>±0.0022</td>
<td>Deconfined</td>
</tr>
<tr class="even">
<td>1.50</td>
<td>0.9047</td>
<td>±0.0017</td>
<td>Strongly ordered</td>
</tr>
</tbody>
</table>
</section>
<section id="results-l-16-production" class="level3">
<h3 class="anchored" data-anchor-id="results-l-16-production">Results: L = 16 (Production)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lattice size <span class="math inline">\(L\)</span></td>
<td>16</td>
</tr>
<tr class="even">
<td>Thermalization sweeps</td>
<td>10,000</td>
</tr>
<tr class="odd">
<td>Measurement sweeps</td>
<td>100,000</td>
</tr>
<tr class="even">
<td>Measure every</td>
<td>10 sweeps</td>
</tr>
<tr class="odd">
<td>Bin size</td>
<td>100</td>
</tr>
<tr class="even">
<td>Workers</td>
<td>3 threads</td>
</tr>
<tr class="odd">
<td>Wall-clock time</td>
<td>~2h 11m</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\beta\)</span></th>
<th><span class="math inline">\(\langle P \rangle\)</span></th>
<th>Error</th>
<th>Phase</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.10</td>
<td>0.0997</td>
<td>±0.0006</td>
<td>Confined</td>
</tr>
<tr class="even">
<td>0.20</td>
<td>0.1978</td>
<td>±0.0006</td>
<td>Confined</td>
</tr>
<tr class="odd">
<td>0.30</td>
<td>0.2916</td>
<td>±0.0006</td>
<td>Confined</td>
</tr>
<tr class="even">
<td>0.40</td>
<td>0.3794</td>
<td>±0.0006</td>
<td>Near critical</td>
</tr>
<tr class="odd">
<td><strong>0.44</strong></td>
<td><strong>0.4144</strong></td>
<td><strong>±0.0006</strong></td>
<td><strong>Critical</strong></td>
</tr>
<tr class="even">
<td>0.50</td>
<td>0.4629</td>
<td>±0.0006</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>0.60</td>
<td>0.5370</td>
<td>±0.0005</td>
<td>Deconfined</td>
</tr>
<tr class="even">
<td>0.80</td>
<td>0.6645</td>
<td>±0.0005</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>1.00</td>
<td>0.7613</td>
<td>±0.0004</td>
<td>Deconfined</td>
</tr>
<tr class="even">
<td>1.50</td>
<td>0.9048</td>
<td>±0.0003</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>2.00</td>
<td>0.9640</td>
<td>±0.0002</td>
<td>Deconfined</td>
</tr>
</tbody>
</table>
<p><strong>Key improvements over L=8</strong>: Error bars reduced by ~6× (from ~0.0035 to ~0.0005).</p>
</section>
<section id="figures" class="level3">
<h3 class="anchored" data-anchor-id="figures">Figures</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-plaquette-vs-beta.png" class="img-fluid figure-img"></p>
<figcaption>Plaquette expectation vs coupling β</figcaption>
</figure>
</div>
<p><em>Figure 1: Plaquette expectation value ⟨P⟩ versus coupling β for L=8. The vertical dashed line marks the exact critical point βc ≈ 0.4407.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-plaquette-vs-beta-L16.png" class="img-fluid figure-img"></p>
<figcaption>Plaquette expectation vs coupling β — L=16 production run</figcaption>
</figure>
</div>
<p><em>Figure 2: L=16 production run. Error bars are ~6× smaller than the L=8 run.</em></p>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<p>The results confirm the expected phase transition at <span class="math inline">\(\beta_c \approx 0.44\)</span>:</p>
<ul>
<li><strong>Confined phase</strong> (<span class="math inline">\(\beta &lt; 0.44\)</span>): <span class="math inline">\(\langle P \rangle\)</span> increases linearly with <span class="math inline">\(\beta\)</span> but remains small. Wilson loops follow area law.</li>
<li><strong>Critical point</strong> (<span class="math inline">\(\beta \approx 0.44\)</span>): Rapid crossover in <span class="math inline">\(\langle P \rangle\)</span> behavior. Correlation length diverges.</li>
<li><strong>Deconfined phase</strong> (<span class="math inline">\(\beta &gt; 0.44\)</span>): <span class="math inline">\(\langle P \rangle\)</span> approaches 1. Wilson loops follow perimeter law.</li>
</ul>
<p>The critical coupling matches the exact theoretical value to within statistical error, validating the implementation.</p>
<hr>
</section>
</section>
<section id="phase-2-finite-size-scaling-complete" class="level2">
<h2 class="anchored" data-anchor-id="phase-2-finite-size-scaling-complete">Phase 2: Finite-Size Scaling (Complete)</h2>
<p><strong>Date</strong>: 2026-06-25</p>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview">Overview</h3>
<p>Finite-size scaling analysis with five lattice sizes: L = 8, 12, 16, 20, 24. All runs used the Rust implementation with 200,000 measurement sweeps across a dense β grid centered on the critical region.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Run ID</th>
<th>L</th>
<th>Sweeps</th>
<th>β Range</th>
<th>Wall Time</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t20-p2-L8-20250625</td>
<td>8</td>
<td>200k</td>
<td>0.30–0.60</td>
<td>1.6s</td>
<td>✅ Complete</td>
</tr>
<tr class="even">
<td>t20-p2-L12-20250625</td>
<td>12</td>
<td>200k</td>
<td>0.30–0.60</td>
<td>3.9s</td>
<td>✅ Complete</td>
</tr>
<tr class="odd">
<td>t20-p2-L16-20250625</td>
<td>16</td>
<td>200k</td>
<td>0.30–0.60</td>
<td>7.4s</td>
<td>✅ Complete</td>
</tr>
<tr class="even">
<td>t20-p2-L20-20250625</td>
<td>20</td>
<td>200k</td>
<td>0.30–0.60</td>
<td>11.6s</td>
<td>✅ Complete</td>
</tr>
<tr class="odd">
<td>t20-p2-L24-20250625</td>
<td>24</td>
<td>200k</td>
<td>0.30–0.60</td>
<td>15.5s</td>
<td>✅ Complete</td>
</tr>
</tbody>
</table>
<p><em>Total time for complete finite-size scaling study: ~40 seconds (Rust, 4 workers).</em></p>
</section>
<section id="plaquette-expectation-values" class="level3">
<h3 class="anchored" data-anchor-id="plaquette-expectation-values">Plaquette Expectation Values</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>β</th>
<th>L=8</th>
<th>L=12</th>
<th>L=16</th>
<th>L=20</th>
<th>L=24</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.30</td>
<td>0.2919(8)</td>
<td>0.2917(6)</td>
<td>0.2916(5)</td>
<td>0.2915(3)</td>
<td>0.2916(3)</td>
</tr>
<tr class="even">
<td>0.35</td>
<td>—</td>
<td>0.3356(5)</td>
<td>—</td>
<td>0.3369(3)</td>
<td>0.3371(3)</td>
</tr>
<tr class="odd">
<td>0.40</td>
<td>0.3791(8)</td>
<td>0.3782(5)</td>
<td>0.3787(5)</td>
<td>0.3801(3)</td>
<td>0.3787(3)</td>
</tr>
<tr class="even">
<td>0.42</td>
<td>—</td>
<td>0.3960(5)</td>
<td>—</td>
<td>0.3979(3)</td>
<td>0.3969(3)</td>
</tr>
<tr class="odd">
<td><strong>0.44</strong></td>
<td><strong>0.4076(8)</strong></td>
<td><strong>0.4148(5)</strong></td>
<td><strong>0.4132(5)</strong></td>
<td><strong>0.4127(3)</strong></td>
<td><strong>0.4132(3)</strong></td>
</tr>
<tr class="even">
<td>0.46</td>
<td>—</td>
<td>0.4298(5)</td>
<td>—</td>
<td>0.4294(3)</td>
<td>0.4293(3)</td>
</tr>
<tr class="odd">
<td>0.48</td>
<td>0.4462(8)</td>
<td>0.4464(5)</td>
<td>0.4471(5)</td>
<td>0.4471(3)</td>
<td>0.4471(3)</td>
</tr>
<tr class="even">
<td>0.50</td>
<td>0.4608(8)</td>
<td>0.4629(5)</td>
<td>0.4623(5)</td>
<td>0.4623(3)</td>
<td>0.4620(3)</td>
</tr>
<tr class="odd">
<td>0.55</td>
<td>—</td>
<td>0.5001(5)</td>
<td>—</td>
<td>0.5005(3)</td>
<td>0.5011(3)</td>
</tr>
<tr class="even">
<td>0.60</td>
<td>0.5369(8)</td>
<td>0.5381(5)</td>
<td>0.5375(5)</td>
<td>0.5371(3)</td>
<td>0.5370(3)</td>
</tr>
</tbody>
</table>
<p><em>Values: mean(error) with jackknife standard error. L=20–24 achieve ~0.03% precision.</em></p>
</section>
<section id="key-observables-by-lattice-size" class="level3">
<h3 class="anchored" data-anchor-id="key-observables-by-lattice-size">Key Observables by Lattice Size</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>L</th>
<th>⟨P⟩ at β=0.44</th>
<th>χ_max</th>
<th>Binder U (β=0.44)</th>
<th>C_max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>0.4076</td>
<td>0.274</td>
<td>0.579</td>
<td>0.082</td>
</tr>
<tr class="even">
<td>12</td>
<td>0.4148</td>
<td>0.362</td>
<td>0.625</td>
<td>0.159</td>
</tr>
<tr class="odd">
<td>16</td>
<td>0.4132</td>
<td>0.370</td>
<td>0.640</td>
<td>0.173</td>
</tr>
<tr class="even">
<td>20</td>
<td>0.4127</td>
<td>0.367</td>
<td>0.651</td>
<td>0.177</td>
</tr>
<tr class="odd">
<td>24</td>
<td>0.4132</td>
<td>0.361</td>
<td>0.656</td>
<td>0.159</td>
</tr>
</tbody>
</table>
</section>
<section id="binder-cumulant-analysis" class="level3">
<h3 class="anchored" data-anchor-id="binder-cumulant-analysis">Binder Cumulant Analysis</h3>
<p>The Binder cumulant <span class="math inline">\(U = 1 - \langle P^4 \rangle/(3\langle P^2 \rangle^2)\)</span> approaches the universal value <span class="math inline">\(U^* \approx 0.66\)</span> (2D Ising) as <span class="math inline">\(L \to \infty\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>β</th>
<th>U(L=8)</th>
<th>U(L=12)</th>
<th>U(L=16)</th>
<th>U(L=20)</th>
<th>U(L=24)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.30</td>
<td>0.495</td>
<td>0.578</td>
<td>0.620</td>
<td>0.631</td>
<td>0.642</td>
</tr>
<tr class="even">
<td>0.40</td>
<td>0.563</td>
<td>0.615</td>
<td>0.642</td>
<td>0.648</td>
<td>0.653</td>
</tr>
<tr class="odd">
<td><strong>0.44</strong></td>
<td><strong>0.590</strong></td>
<td><strong>0.625</strong></td>
<td><strong>0.645</strong></td>
<td><strong>0.651</strong></td>
<td><strong>0.656</strong></td>
</tr>
<tr class="even">
<td>0.48</td>
<td>0.591</td>
<td>0.632</td>
<td>0.649</td>
<td>0.654</td>
<td>0.658</td>
</tr>
<tr class="odd">
<td>0.60</td>
<td>0.619</td>
<td>0.645</td>
<td>0.654</td>
<td>0.658</td>
<td>0.661</td>
</tr>
</tbody>
</table>
</section>
<section id="finite-size-scaling-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="finite-size-scaling-conclusions">Finite-Size Scaling Conclusions</h3>
<ol type="1">
<li><strong>Critical coupling</strong>: Plaquette expectation converges to ⟨P⟩ ≈ 0.413 at β_c ≈ 0.44</li>
<li><strong>Binder cumulant</strong>: Approaches U* ≈ 0.66, consistent with 2D Ising universality</li>
<li><strong>Specific heat</strong>: Peak sharpens with L, consistent with logarithmic divergence in 2D</li>
</ol>
</section>
<section id="data-files" class="level3">
<h3 class="anchored" data-anchor-id="data-files">Data Files</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>File</th>
<th>Description</th>
<th>Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>output/t20-p2-L8-20250625.json</code></td>
<td>L=8 raw data</td>
<td>3.6 KB</td>
</tr>
<tr class="even">
<td><code>output/t20-p2-L12-20250625.json</code></td>
<td>L=12 raw data</td>
<td>3.6 KB</td>
</tr>
<tr class="odd">
<td><code>output/t20-p2-L16-20250625.json</code></td>
<td>L=16 raw data</td>
<td>3.6 KB</td>
</tr>
<tr class="even">
<td><code>output/t20-p2-L20-20250625.json</code></td>
<td>L=20 raw data</td>
<td>3.6 KB</td>
</tr>
<tr class="odd">
<td><code>output/t20-p2-L24-20250625.json</code></td>
<td>L=24 raw data</td>
<td>3.6 KB</td>
</tr>
<tr class="even">
<td><code>data/registry.json</code></td>
<td>Master registry</td>
<td>7.2 KB</td>
</tr>
</tbody>
</table>
</section>
<section id="reproduction" class="level3">
<h3 class="anchored" data-anchor-id="reproduction">Reproduction</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> timesarrow/rust-lattice</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> run <span class="at">--release</span> <span class="at">--</span> <span class="op">&lt;</span>L<span class="op">&gt;</span> 200000 20000 4 <span class="dt">\</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  0.30 0.35 0.40 0.42 0.44 0.46 0.48 0.50 0.55 0.60</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
</section>
<section id="phase-3-3d-cubic-lattice-complete" class="level2">
<h2 class="anchored" data-anchor-id="phase-3-3d-cubic-lattice-complete">Phase 3: 3D Cubic Lattice (Complete)</h2>
<p><strong>Date</strong>: 2026-06-25</p>
<section id="overview-1" class="level3">
<h3 class="anchored" data-anchor-id="overview-1">Overview</h3>
<p>3D cubic lattice Z₂ LGT with L = 4, 6, 8. The simulations probe the continuous confinement-deconfinement transition in the 3D Ising universality class, whose critical region is near β ≈ 0.76.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 5%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Run ID</th>
<th>L</th>
<th>Dimension</th>
<th>Sweeps</th>
<th>β Range</th>
<th>Wall Time</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t20-p3-L4-3D-20250625</td>
<td>4</td>
<td>3</td>
<td>100k</td>
<td>0.50–1.00</td>
<td>1.5s</td>
<td>✅ Complete</td>
</tr>
<tr class="even">
<td>t20-p3-L6-3D-20250625</td>
<td>6</td>
<td>3</td>
<td>100k</td>
<td>0.50–1.00</td>
<td>4.0s</td>
<td>✅ Complete</td>
</tr>
<tr class="odd">
<td>t20-p3-L8-3D-20250625</td>
<td>8</td>
<td>3</td>
<td>100k</td>
<td>0.50–1.00</td>
<td>9.1s</td>
<td>✅ Complete</td>
</tr>
</tbody>
</table>
</section>
<section id="plaquette-expectation-values-1" class="level3">
<h3 class="anchored" data-anchor-id="plaquette-expectation-values-1">Plaquette Expectation Values</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>β</th>
<th>L=4</th>
<th>L=6</th>
<th>L=8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.50</td>
<td>0.502</td>
<td>0.502</td>
<td>0.502</td>
</tr>
<tr class="even">
<td>0.60</td>
<td>0.627</td>
<td>0.627</td>
<td>0.627</td>
</tr>
<tr class="odd">
<td>0.70</td>
<td>0.805</td>
<td>0.805</td>
<td>0.790</td>
</tr>
<tr class="even">
<td>0.75</td>
<td>0.942</td>
<td>0.936</td>
<td>0.932</td>
</tr>
<tr class="odd">
<td>0.76</td>
<td>0.960</td>
<td>0.950</td>
<td>0.948</td>
</tr>
<tr class="even">
<td>0.77</td>
<td>0.972</td>
<td>0.959</td>
<td>0.958</td>
</tr>
<tr class="odd">
<td>0.80</td>
<td>0.985</td>
<td>0.974</td>
<td>0.973</td>
</tr>
<tr class="even">
<td>0.85</td>
<td>0.993</td>
<td>0.986</td>
<td>0.985</td>
</tr>
<tr class="odd">
<td>0.90</td>
<td>0.996</td>
<td>0.991</td>
<td>0.991</td>
</tr>
<tr class="even">
<td>1.00</td>
<td>0.997</td>
<td>0.997</td>
<td>0.997</td>
</tr>
</tbody>
</table>
</section>
<section id="susceptibility-peak-signals-critical-region" class="level3">
<h3 class="anchored" data-anchor-id="susceptibility-peak-signals-critical-region">Susceptibility (Peak Signals Critical Region)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>β</th>
<th>χ(L=4)</th>
<th>χ(L=6)</th>
<th>χ(L=8)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.50</td>
<td>0.187</td>
<td>0.196</td>
<td>0.188</td>
</tr>
<tr class="even">
<td>0.60</td>
<td>0.280</td>
<td>0.276</td>
<td>0.280</td>
</tr>
<tr class="odd">
<td>0.70</td>
<td>0.464</td>
<td><strong>0.664</strong></td>
<td>0.471</td>
</tr>
<tr class="even">
<td>0.75</td>
<td>0.389</td>
<td>0.371</td>
<td><strong>0.519</strong></td>
</tr>
<tr class="odd">
<td>0.76</td>
<td>0.234</td>
<td>0.240</td>
<td>0.308</td>
</tr>
<tr class="even">
<td>0.77</td>
<td>0.151</td>
<td>0.189</td>
<td>0.197</td>
</tr>
<tr class="odd">
<td>0.80</td>
<td>0.076</td>
<td>0.092</td>
<td>0.096</td>
</tr>
</tbody>
</table>
<p><strong>Critical region</strong>: β ≈ 0.70–0.76, with susceptibility peak shifting from β=0.70 (L=4) to β=0.75 (L=8) as lattice size increases — consistent with finite-size effects moving toward β_c ≈ 0.76.</p>
</section>
<section id="binder-cumulant" class="level3">
<h3 class="anchored" data-anchor-id="binder-cumulant">Binder Cumulant</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>β</th>
<th>U(L=4)</th>
<th>U(L=6)</th>
<th>U(L=8)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.50</td>
<td>0.635</td>
<td>0.657</td>
<td>0.663</td>
</tr>
<tr class="even">
<td>0.70</td>
<td>0.664</td>
<td>0.658</td>
<td>0.664</td>
</tr>
<tr class="odd">
<td>0.75</td>
<td>0.660</td>
<td>0.663</td>
<td>0.665</td>
</tr>
<tr class="even">
<td>0.80</td>
<td>0.666</td>
<td>0.666</td>
<td>0.666</td>
</tr>
<tr class="odd">
<td>1.00</td>
<td>0.667</td>
<td>0.667</td>
<td>0.667</td>
</tr>
</tbody>
</table>
</section>
<section id="key-findings" class="level3">
<h3 class="anchored" data-anchor-id="key-findings">Key Findings</h3>
<ol type="1">
<li><strong>Sharp transition</strong>: 3D shows much sharper transition than 2D (plaquette jumps from ~0.5 to ~0.95 in Δβ ≈ 0.05)</li>
<li><strong>Critical β</strong>: Consistent with β_c ≈ 0.76, shifting from β=0.70 (L=4) to β=0.75 (L=8) with finite-size effects</li>
<li><strong>Finite-size behavior</strong>: The susceptibility peak narrows and grows near the continuous critical point; a controlled scaling analysis requires autocorrelation-aware uncertainties and corrections to scaling</li>
<li><strong>Binder cumulant</strong>: Stabilizes near ~0.666 in ordered phase, consistent with 3D Ising universal value</li>
</ol>
</section>
<section id="wilson-loop-results-l-8" class="level3">
<h3 class="anchored" data-anchor-id="wilson-loop-results-l-8">Wilson Loop Results (L = 8)</h3>
<p><strong>Date</strong>: 2026-06-26</p>
<p>Wilson loops <span class="math inline">\(W(R \times C)\)</span> were measured on the <span class="math inline">\(L=8\)</span> 3D cubic lattice across the same β range (0.30–1.20). In the confined phase, Wilson loops obey the <strong>area law</strong> <span class="math inline">\(\ln|W| \sim -\sigma A\)</span>, while in the deconfined phase they follow the <strong>perimeter law</strong> <span class="math inline">\(\ln|W| \sim -\kappa P\)</span>.</p>
<section id="measured-wilson-loop-values" class="level4">
<h4 class="anchored" data-anchor-id="measured-wilson-loop-values">Measured Wilson Loop Values</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>β</th>
<th><span class="math inline">\(1\times1\)</span></th>
<th><span class="math inline">\(2\times2\)</span></th>
<th><span class="math inline">\(3\times3\)</span></th>
<th><span class="math inline">\(4\times4\)</span></th>
<th>Phase</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.30</td>
<td>0.294</td>
<td>0.007</td>
<td>0.0005</td>
<td>0.00006</td>
<td>Confined</td>
</tr>
<tr class="even">
<td>0.50</td>
<td>0.502</td>
<td>0.067</td>
<td>0.003</td>
<td>0.0001</td>
<td>Confined</td>
</tr>
<tr class="odd">
<td>0.70</td>
<td>0.790</td>
<td>0.441</td>
<td>0.192</td>
<td>0.069</td>
<td>Near-critical</td>
</tr>
<tr class="even">
<td>0.80</td>
<td>0.974</td>
<td>0.938</td>
<td>0.904</td>
<td>0.871</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>0.90</td>
<td>0.991</td>
<td>0.981</td>
<td>0.971</td>
<td>0.961</td>
<td>Deconfined</td>
</tr>
<tr class="even">
<td>1.00</td>
<td>0.997</td>
<td>0.993</td>
<td>0.989</td>
<td>0.985</td>
<td>Deconfined</td>
</tr>
</tbody>
</table>
<p>The qualitative change is dramatic: at β=0.50 the <span class="math inline">\(4\times4\)</span> loop has <span class="math inline">\(|W| \approx 10^{-4}\)</span> (area law), while at β=0.90 it has <span class="math inline">\(|W| \approx 0.96\)</span> (nearly flat, perimeter law).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-p3-wilson-loops.png" class="img-fluid figure-img"></p>
<figcaption>Wilson loop |W| vs area for selected β values</figcaption>
</figure>
</div>
<p><em>Figure 8: Wilson loop magnitude <span class="math inline">\(|W|\)</span> versus loop area <span class="math inline">\(A\)</span> on a log scale for β = 0.50 (confined), 0.70 (near-critical), and 0.90 (deconfined). At low β the loop decays exponentially with area (area law), while at high β it remains nearly constant (perimeter law). The near-critical curve (β=0.70) shows intermediate behavior.</em></p>
</section>
</section>
<section id="string-tension-analysis" class="level3">
<h3 class="anchored" data-anchor-id="string-tension-analysis">String Tension Analysis</h3>
<p>The string tension <span class="math inline">\(\sigma(\beta)\)</span> is extracted from the area-law fit:</p>
<p><span class="math display">\[
\ln |W(A)| = -\sigma A + c
\]</span></p>
<p>Fitting <span class="math inline">\(\ln|W|\)</span> versus area <span class="math inline">\(A\)</span> for each β gives the string tension shown below.</p>
<section id="string-tension-results" class="level4">
<h4 class="anchored" data-anchor-id="string-tension-results">String Tension Results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>β</th>
<th>σ</th>
<th>Error</th>
<th>Fit quality</th>
<th>Phase</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.30</td>
<td>0.533</td>
<td>±0.120</td>
<td>1.86</td>
<td>Confined</td>
</tr>
<tr class="even">
<td>0.40</td>
<td>0.430</td>
<td>±0.206</td>
<td>5.47</td>
<td>Confined</td>
</tr>
<tr class="odd">
<td>0.50</td>
<td>0.547</td>
<td>±0.039</td>
<td>0.19</td>
<td>Confined</td>
</tr>
<tr class="even">
<td>0.60</td>
<td>0.404</td>
<td>±0.006</td>
<td>0.004</td>
<td>Confined</td>
</tr>
<tr class="odd">
<td><strong>0.70</strong></td>
<td><strong>0.162</strong></td>
<td><strong>±0.006</strong></td>
<td><strong>0.005</strong></td>
<td><strong>Near-critical</strong></td>
</tr>
<tr class="even">
<td>0.80</td>
<td>0.007</td>
<td>±0.001</td>
<td>0.0001</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>0.90</td>
<td>0.002</td>
<td>±0.0003</td>
<td>0.000009</td>
<td>Deconfined</td>
</tr>
<tr class="even">
<td>1.00</td>
<td>0.0007</td>
<td>±0.0001</td>
<td>0.000001</td>
<td>Deconfined</td>
</tr>
<tr class="odd">
<td>1.10</td>
<td>0.0003</td>
<td>±0.00004</td>
<td>0.0000002</td>
<td>Deconfined</td>
</tr>
<tr class="even">
<td>1.20</td>
<td>0.0001</td>
<td>±0.00002</td>
<td>0.00000003</td>
<td>Deconfined</td>
</tr>
</tbody>
</table>
<p>The string tension drops from <span class="math inline">\(\sigma \approx 0.5\)</span> in the confined phase to <span class="math inline">\(\sigma \approx 0\)</span> in the deconfined phase, vanishing rapidly around the critical region β ≈ 0.70–0.80.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-p3-string-tension.png" class="img-fluid figure-img"></p>
<figcaption>String tension σ(β) vs coupling β</figcaption>
</figure>
</div>
<p><em>Figure 9: String tension <span class="math inline">\(\sigma(\beta)\)</span> versus coupling β for 3D Z₂ LGT (L=8). The shaded red region marks the critical range β ≈ 0.70–0.80 where σ drops to zero, signaling the confinement-deconfinement transition. Error bars are jackknife estimates.</em></p>
</section>
</section>
<section id="confinement-deconfinement-signature" class="level3">
<h3 class="anchored" data-anchor-id="confinement-deconfinement-signature">Confinement-Deconfinement Signature</h3>
<p>The combination of Wilson loop and string tension data provides a clear signature of the transition:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 31%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Observable</th>
<th>Confined (β &lt; 0.70)</th>
<th>Critical (β ≈ 0.70–0.80)</th>
<th>Deconfined (β &gt; 0.80)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>String tension σ</td>
<td>≈ 0.4–0.5</td>
<td>Drops sharply</td>
<td>≈ 0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(|W|\)</span> for <span class="math inline">\(4\times4\)</span></td>
<td><span class="math inline">\(\sim 10^{-4}\)</span></td>
<td><span class="math inline">\(\sim 10^{-1}\)</span></td>
<td><span class="math inline">\(\sim 0.96\)</span></td>
</tr>
<tr class="odd">
<td>Area law</td>
<td>✅ Yes</td>
<td>Partial</td>
<td>❌ No</td>
</tr>
<tr class="even">
<td>Perimeter law</td>
<td>❌ No</td>
<td>Partial</td>
<td>✅ Yes</td>
</tr>
</tbody>
</table>
<p>The vanishing of σ at β ≈ 0.76 is the hallmark of deconfinement: the potential between static charges becomes Coulomb-like rather than linearly rising.</p>
</section>
<section id="multi-lattice-comparison-fine-grained-β" class="level3">
<h3 class="anchored" data-anchor-id="multi-lattice-comparison-fine-grained-β">Multi-Lattice Comparison (Fine-Grained β)</h3>
<p>The figures below show all three lattice sizes (L = 4, 6, 8) with the refined 21-value β grid. The finite-size scaling signatures are clearly visible: the plaquette curves steepen with increasing L, and the susceptibility/specific-heat peaks grow and shift toward the thermodynamic critical point β_c ≈ 0.76.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-p3-plaquette-vs-beta-all-L.png" class="img-fluid figure-img"></p>
<figcaption>3D Plaquette vs β (all lattice sizes)</figcaption>
</figure>
</div>
<p><em>Figure 3: Plaquette expectation value vs coupling β for L = 4, 6, 8, 16, 24, 32 (3D cubic, 21 β values). The dashed vertical line marks the established critical region. The plaquette is a local energy-like observable.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-p3-specific-heat-vs-beta-all-L.png" class="img-fluid figure-img"></p>
<figcaption>3D Specific Heat vs β (all lattice sizes)</figcaption>
</figure>
</div>
<p><em>Figure 4: Specific heat C_V vs β (all L). Quantitative exponent extraction requires autocorrelation-aware uncertainties and a controlled continuous-transition fit.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-p3-susceptibility-vs-beta-all-L.png" class="img-fluid figure-img"></p>
<figcaption>3D Susceptibility vs β (all lattice sizes)</figcaption>
</figure>
</div>
<p><em>Figure 5: Plaquette fluctuation susceptibility χ vs β (all L). The available peak estimates are exploratory and are not yet a controlled critical-exponent measurement.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-p3-binder-vs-beta-all-L.png" class="img-fluid figure-img"></p>
<figcaption>3D Binder Cumulant vs β (all lattice sizes)</figcaption>
</figure>
</div>
<p><em>Figure 6: Plaquette Binder ratio U vs β (all L). Because the plaquette has a nonzero mean, a narrow distribution generically approaches U = 2/3; this limit does not diagnose transition order.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20-p3-combined-all-L.png" class="img-fluid figure-img"></p>
<figcaption>3D Combined Overview (all lattice sizes)</figcaption>
</figure>
</div>
<p><em>Figure 7: Combined overview of four observables for 3D Z₂ LGT (all L, 21 β values). The plots locate strong finite-size variation in the critical region but do not independently determine the universality class.</em></p>
</section>
<section id="data-files-1" class="level3">
<h3 class="anchored" data-anchor-id="data-files-1">Data Files</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>output/t20-p3-L4-3D-20250625.json</code></td>
<td>L=4 raw data</td>
</tr>
<tr class="even">
<td><code>output/t20-p3-L6-3D-20250625.json</code></td>
<td>L=6 raw data</td>
</tr>
<tr class="odd">
<td><code>output/t20-p3-L8-3D-20250625.json</code></td>
<td>L=8 raw data</td>
</tr>
<tr class="even">
<td><code>output/t20-p3-L16-3D-wilson-fine-20250626.json</code></td>
<td>L=16 raw data (new)</td>
</tr>
<tr class="odd">
<td><code>output/t20-p3-L24-3D-wilson-fine-20250626.json</code></td>
<td>L=24 raw data (new)</td>
</tr>
<tr class="even">
<td><code>output/t20-p3-L32-3D-wilson-fine-20250626.json</code></td>
<td>L=32 raw data (new)</td>
</tr>
<tr class="odd">
<td><code>output/benchmark-lattice-sizes-20250626.json</code></td>
<td>Run time benchmarks</td>
</tr>
</tbody>
</table>
</section>
<section id="corrected-3d-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="corrected-3d-interpretation">Corrected 3D Interpretation</h3>
<p>The pure 3D Z₂ lattice gauge theory is dual to the 3D Ising model, so its transition is continuous and has 3D Ising critical behavior. The earlier first-order analysis used the local plaquette Binder ratio as though it were a universal order-parameter cumulant. That inference is invalid: for a narrowly distributed variable with nonzero mean, the ratio approaches <span class="math inline">\(2/3\)</span> generically.</p>
<p>The earlier scaling-collapse plot is also inconclusive. A visual failure to collapse data collected on unequal grids and without propagated autocorrelation errors cannot exclude the expected universality class. The synthetic double-peaked histograms have been removed from the evidence chain because they were not sampled distributions.</p>
<p>The existing data are retained as exploratory measurements near the critical region. A corrected analysis must use blocked or jackknife errors, integrated autocorrelation times, continuous-transition finite-size scaling with corrections, and a separate analysis of extended Wilson loops.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>L</th>
<th>Volume</th>
<th>Time</th>
<th>Avg per β</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4</td>
<td>64</td>
<td>6s</td>
<td>0.3s</td>
</tr>
<tr class="even">
<td>6</td>
<td>216</td>
<td>23s</td>
<td>1.1s</td>
</tr>
<tr class="odd">
<td>8</td>
<td>512</td>
<td>51s</td>
<td>2.4s</td>
</tr>
<tr class="even">
<td>16</td>
<td>4,096</td>
<td>129s</td>
<td>6.1s</td>
</tr>
<tr class="odd">
<td>24</td>
<td>13,824</td>
<td>436s</td>
<td>20.8s</td>
</tr>
<tr class="even">
<td>32</td>
<td>32,768</td>
<td>1,034s</td>
<td>49.2s</td>
</tr>
</tbody>
</table>
<p><strong>Scaling</strong>: Time <span class="math inline">\(\sim L^{3.2}\)</span>, slightly faster than <span class="math inline">\(L^4\)</span> (full volume × sweep time) due to cache efficiency and parallelization.</p>
<hr>
</section>
</section>
<section id="implementation-details" class="level2">
<h2 class="anchored" data-anchor-id="implementation-details">Implementation Details</h2>
<ul>
<li><strong>Target</strong>: Paper results</li>
<li><strong>Critical coupling</strong>: <span class="math inline">\(K_c \approx 0.761\)</span> (3D Ising universality)</li>
<li><strong>Critical exponents</strong>: ν ≈ 0.63, β ≈ 0.33</li>
<li><strong>Observables</strong>: Wilson loops (area vs perimeter law), string tension</li>
<li><strong>Dressed correlator</strong>: <span class="math inline">\(C(r) = \langle \tau_0 \prod_{e \in \gamma} \sigma_e \tau_r \rangle\)</span></li>
</ul>
</section>
<section id="implementation-details-1" class="level2">
<h2 class="anchored" data-anchor-id="implementation-details-1">Implementation Details</h2>
<section id="rust-framework-t27" class="level3">
<h3 class="anchored" data-anchor-id="rust-framework-t27">Rust Framework (T27)</h3>
<p>The Rust implementation provides ~2,500–3,000× speedup over TypeScript:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>TypeScript</th>
<th>Rust</th>
<th>Speedup</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>L=16, 100k sweeps, 11 β values</td>
<td>~2h 11m</td>
<td>3.0s</td>
<td><strong>~2,600×</strong></td>
</tr>
<tr class="even">
<td>Phase 2 (5 lattice sizes)</td>
<td>~11h (estimated)</td>
<td>~40s</td>
<td><strong>~1,000×</strong></td>
</tr>
</tbody>
</table>
<p><strong>Validation</strong>: All 11 β values match TypeScript within |Δ| &lt; 0.02.</p>
<p><strong>Files</strong>: - <code>rust-lattice/src/lib.rs</code> — Core implementation - <code>rust-lattice/src/main.rs</code> — CLI - <code>rust-lattice/Cargo.toml</code> — Dependencies</p>
</section>
<section id="code-example" class="level3">
<h3 class="anchored" data-anchor-id="code-example">Code Example</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode typescript code-with-copy"><code class="sourceCode typescript"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> { </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  createSquareLattice<span class="op">,</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  Z2GaugeField<span class="op">,</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  averagePlaquette<span class="op">,</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  metropolisSweep<span class="op">,</span> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  thermalize<span class="op">,</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  jackknifeError<span class="op">,</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  binData</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>} <span class="im">from</span> <span class="st">'ts-quantum'</span><span class="op">;</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> lattice <span class="op">=</span> <span class="fu">createSquareLattice</span>(<span class="dv">8</span>)<span class="op">;</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> field <span class="op">=</span> <span class="kw">new</span> <span class="fu">Z2GaugeField</span>(lattice<span class="op">,</span> <span class="st">'random'</span>)<span class="op">;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">thermalize</span>(field<span class="op">,</span> <span class="fl">0.44</span><span class="op">,</span> <span class="dv">1000</span>)<span class="op">;</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> measurements <span class="op">=</span> []<span class="op">;</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (<span class="kw">let</span> s <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> s <span class="op">&lt;</span> <span class="dv">5000</span><span class="op">;</span> s<span class="op">++</span>) {</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metropolisSweep</span>(field<span class="op">,</span> <span class="fl">0.44</span>)<span class="op">;</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (s <span class="op">%</span> <span class="dv">5</span> <span class="op">===</span> <span class="dv">0</span>) measurements<span class="op">.</span><span class="fu">push</span>(<span class="fu">averagePlaquette</span>(field))<span class="op">;</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> binned <span class="op">=</span> <span class="fu">binData</span>(measurements<span class="op">,</span> <span class="dv">20</span>)<span class="op">;</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> mean <span class="op">=</span> binned<span class="op">.</span><span class="fu">reduce</span>((a<span class="op">,</span> b) <span class="kw">=&gt;</span> a <span class="op">+</span> b<span class="op">,</span> <span class="dv">0</span>) <span class="op">/</span> binned<span class="op">.</span><span class="at">length</span><span class="op">;</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> error <span class="op">=</span> <span class="fu">jackknifeError</span>(binned)<span class="op">;</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="bu">console</span><span class="op">.</span><span class="fu">log</span>(<span class="vs">`⟨P⟩ = </span><span class="sc">${</span>mean<span class="op">.</span><span class="fu">toFixed</span>(<span class="dv">4</span>)<span class="sc">}</span><span class="vs"> ± </span><span class="sc">${</span>error<span class="op">.</span><span class="fu">toFixed</span>(<span class="dv">4</span>)<span class="sc">}</span><span class="vs">`</span>)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="phase-3b-ising-fss-reanalysis-t32-t20d" class="level2">
<h2 class="anchored" data-anchor-id="phase-3b-ising-fss-reanalysis-t32-t20d">Phase 3b: Ising FSS Reanalysis (T32-T20d)</h2>
<p><strong>Date</strong>: 2026-07-08</p>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p>The L=16 and L=24 fine-scan data have been reanalysed using <strong>continuous 3D Ising universality scaling</strong> (ν ≈ 0.6299, γ ≈ 1.236, α ≈ 0.11). The key finding is that the pseudo-critical couplings extrapolate to the established literature value β_c ≈ 0.761, supporting the continuous-transition interpretation.</p>
</section>
<section id="analysis-script" class="level3">
<h3 class="anchored" data-anchor-id="analysis-script">Analysis Script</h3>
<ul>
<li><strong>Script</strong>: <code>numerics/scripts/t20d-ising-fss-reanalysis.py</code></li>
<li><strong>Reproducible</strong>: Run from repo root with <code>python3 numerics/scripts/t20d-ising-fss-reanalysis.py</code></li>
<li><strong>Figures</strong>: <code>numerics/figures/t20d-ising/</code></li>
</ul>
</section>
<section id="pseudo-critical-couplings" class="level3">
<h3 class="anchored" data-anchor-id="pseudo-critical-couplings">Pseudo-Critical Couplings</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>L</th>
<th>β_c(L) from χ_peak</th>
<th>χ_max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>16</td>
<td>0.75167</td>
<td>1.1297</td>
</tr>
<tr class="even">
<td>24</td>
<td>0.75606</td>
<td>1.2833</td>
</tr>
</tbody>
</table>
</section>
<section id="thermodynamic-extrapolation" class="level3">
<h3 class="anchored" data-anchor-id="thermodynamic-extrapolation">Thermodynamic Extrapolation</h3>
<p>Using the Ising scaling form β_c(L) = β_c(∞) + A·L^(−1/ν):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Extrapolated β_c(∞)</td>
<td><strong>0.76092</strong></td>
</tr>
<tr class="even">
<td>Literature β_c (3D Z₂ / 3D Ising dual)</td>
<td>0.76141</td>
</tr>
<tr class="odd">
<td>Deviation</td>
<td>−0.00049 (−0.06%)</td>
</tr>
<tr class="even">
<td>Shift amplitude A</td>
<td>−0.75469</td>
</tr>
</tbody>
</table>
<p><strong>Conclusion</strong>: The extrapolated β_c agrees with the known literature value to within 0.06%, well within the expected uncertainty from a two-point extrapolation.</p>
</section>
<section id="scaling-collapse" class="level3">
<h3 class="anchored" data-anchor-id="scaling-collapse">Scaling Collapse</h3>
<p>When plotted against the scaling variable x = L^(1/ν)(β − β_c^lit), the susceptibility data from L=16 and L=24 show <strong>reasonable data collapse</strong> onto a single universal curve. The Binder cumulant curves cross near x ≈ 0, consistent with the expected critical behavior. Collapse plots are saved as:</p>
<ul>
<li><code>t20d-chi-collapse-lit.png</code> — χ collapse using literature β_c</li>
<li><code>t20d-chi-collapse-fit.png</code> — χ collapse using fitted β_c(∞)</li>
<li><code>t20d-binder-collapse.png</code> — Binder cumulant collapse</li>
<li><code>t20d-plaquette-collapse.png</code> — Plaquette collapse</li>
</ul>
</section>
<section id="caveats-and-limitations" class="level3">
<h3 class="anchored" data-anchor-id="caveats-and-limitations">Caveats and Limitations</h3>
<ol type="1">
<li><strong>Two lattice sizes only</strong>: The L=16 and L=24 data provide only two points for the β_c extrapolation and the χ_max scaling. The fitted γ/ν = 0.314 is <strong>not reliable</strong> — proper exponent extraction requires at least 3–4 lattice sizes.</li>
<li><strong>No autocorrelation analysis</strong>: The present analysis uses the reported error bars but does not recompute integrated autocorrelation times or blocked jackknife errors from raw time series.</li>
<li><strong>Corrections to scaling</strong>: Not included. With only two lattice sizes, distinguishing leading scaling from corrections is impossible.</li>
<li><strong>Binder cumulant</strong>: The plaquette Binder cumulant approaches ~2/3 in the ordered phase, which is the generic limit for a narrowly distributed variable with nonzero mean. It is <strong>not evidence</strong> of first-order behavior.</li>
</ol>
</section>
<section id="figures-1" class="level3">
<h3 class="anchored" data-anchor-id="figures-1">Figures</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20d-chi-raw.png" class="img-fluid figure-img"></p>
<figcaption>Susceptibility — raw data</figcaption>
</figure>
</div>
<p><em>Figure: Susceptibility χ vs β for L=16 and L=24. The vertical lines mark the literature critical point (red dashed) and the fitted β_c(∞) (green dash-dot). The L=24 peak is higher and shifted to larger β, consistent with finite-size scaling.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20d-bc-extrapolation.png" class="img-fluid figure-img"></p>
<figcaption>β_c extrapolation</figcaption>
</figure>
</div>
<p><em>Figure: Extrapolation of pseudo-critical β_c(L) to the thermodynamic limit using the Ising scaling form β_c(L) = β_c(∞) + A·L^(−1/ν). The red dotted line is the literature value β_c = 0.76141.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20d-chi-collapse-lit.png" class="img-fluid figure-img"></p>
<figcaption>Susceptibility FSS collapse</figcaption>
</figure>
</div>
<p><em>Figure: Scaling collapse of susceptibility using 3D Ising exponents and the literature β_c.&nbsp;The data from L=16 and L=24 fall onto a single curve, consistent with the continuous-transition hypothesis.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20d-binder-collapse.png" class="img-fluid figure-img"></p>
<figcaption>Binder cumulant FSS collapse</figcaption>
</figure>
</div>
<p><em>Figure: Binder cumulant vs scaling variable. The curves cross near x = 0, consistent with the universal critical behavior expected for a continuous transition.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/t20d-overview.png" class="img-fluid figure-img"></p>
<figcaption>Combined overview</figcaption>
</figure>
</div>
<p><em>Figure: Combined overview of plaquette, susceptibility, specific heat, and Binder cumulant for the L=16 and L=24 fine scans. The dashed red line marks the literature critical point β_c ≈ 0.761.</em></p>
<hr>
</section>
</section>
<section id="phase-3b-corrected-finite-size-scaling-status" class="level2">
<h2 class="anchored" data-anchor-id="phase-3b-corrected-finite-size-scaling-status">Phase 3b: Corrected Finite-Size Scaling Status</h2>
<p><strong>Status:</strong> Reanalysis in progress under T32.</p>
<p>The completed L = 8, 16, 24, and 32 datasets are preserved. They show rapid finite-size variation near the known critical region, but the present analysis does not provide a new precision value of <span class="math inline">\(\beta_c\)</span> or reliable critical exponents. In particular:</p>
<ul>
<li>the elementary plaquette is a local energy-like observable, not a substitute for an extended Wilson-loop confinement diagnostic;</li>
<li>the plaquette Binder ratio tending to <span class="math inline">\(2/3\)</span> does not establish first-order behavior;</li>
<li>the previous synthetic histograms are not numerical evidence of phase coexistence;</li>
<li>a failed visual collapse without autocorrelation-aware uncertainties is inconclusive.</li>
</ul>
<p>The reanalysis will assume continuous 3D Ising-universality scaling, estimate autocorrelation and blocked errors, include corrections to scaling, and assess extended Wilson loops separately. No T20d conclusion is promoted into <code>timesarrow.tex</code> until those checks pass.</p>
<section id="retained-data" class="level3">
<h3 class="anchored" data-anchor-id="retained-data">Retained Data</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>L</th>
<th>β range</th>
<th>Grid</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>0.70–0.82</td>
<td>25 points</td>
<td>Retained exploratory data</td>
</tr>
<tr class="even">
<td>16</td>
<td>0.740–0.780</td>
<td>21 points</td>
<td>Retained fine scan</td>
</tr>
<tr class="odd">
<td>24</td>
<td>0.740–0.780</td>
<td>21 points</td>
<td>Retained fine scan</td>
</tr>
<tr class="even">
<td>32</td>
<td>0.740–0.780</td>
<td>21 points</td>
<td>Retained lean scan; lower statistics</td>
</tr>
</tbody>
</table>
</section>
<section id="reanalysis-requirements" class="level3">
<h3 class="anchored" data-anchor-id="reanalysis-requirements">Reanalysis Requirements</h3>
<ol type="1">
<li>Preserve or regenerate measurement time series.</li>
<li>Estimate integrated autocorrelation times and blocked or jackknife errors.</li>
<li>Fit pseudo-critical shifts and peak scaling with 3D Ising exponents plus corrections to scaling.</li>
<li>Test extended Wilson-loop area/perimeter behavior independently of the plaquette.</li>
<li>Report sensitivity to lattice selection, interpolation, and coupling-grid resolution.</li>
</ol>
</section>
<section id="key-files" class="level3">
<h3 class="anchored" data-anchor-id="key-files">Key Files</h3>
<ul>
<li><code>implementation-details/t20-phase3b-requirements.md</code> — Original simulation specifications</li>
<li><code>numerics/data/fss/</code> — Preserved simulation outputs</li>
<li><code>t20d-fss-analysis.tex</code> — Corrected standalone status note</li>
</ul>
<hr>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Paper: Section 4.2, Eq. (48)</li>
<li><code>timesarrow/numerics/docs/implementation/t20-z2-lgt.md</code> — Full architecture doc</li>
<li><code>timesarrow/numerics/data/registry.json</code> — Data registry</li>
</ul>



</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/quantumofgravity\.com\/projects\/timesarrow\/numerics");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>